language: julia

os:
  - linux

notifications:
  email: false

julia:
  #- 0.6
  - nightly

matrix:
  allow_failures:
  - julia: nightly

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("LogParser")'
